sudo: required
services: 
  - docker
  
before_install:
  - docker build -t sganguly24/sgcodes:nginx-prod -f Dockerfile.dev .

script:
  - docker run sganguly24/sgcodes:nginx-prod npm run test -- --coverage 